export const imageTypes = [
  { label: "NDVI", value: "ndvi" },
  { label: "NDWI", value: "ndwi" },
  { label: "EVAPO", value: "evapo" },
  { label: "NDMI", value: "ndmi" },
  { label: "EVI", value: "evi" },
  { label: "RVI", value: "rvi" },
  { label: "RSM", value: "rsm" },
  { label: "NDRE", value: "ndre" },
  { label: "VARI", value: "vari" },
  { label: "SAVI", value: "savi" },
  { label: "AVI", value: "avi" },
  { label: "BSI", value: "bsi" },
  { label: "SI", value: "si" },
  { label: "SOC", value: "soc" },
  { label: "TCI", value: "tci" },
  { label: "ETCI", value: "etci" },
  { label: "HYBRID", value: "hybrid" },
  { label: "COLORBLIND", value: "hybrid_blind" },
  { label: "DEM", value: "dem" },
  { label: "LULC", value: "lulc" },
]
